### ISSUE TITLE
Setup Kotlin Spring Boot Project in Karavan repo

### ISSUE THREAD

**Issue by notmandatory** [notmandatory/karavan#2]
https://spring.io/guides/tutorials/spring-boot-kotlin/

group: `bitcoindevkit.org` 
artifact id:  `karavan`

Add bdk dependency:
```
implementation("org.bitcoindevkit:bdk-jvm:0.2.2")
```

**Comment by abdulla-khalid** [comment]
do not see an "artifact id" in the files to change, only "group" inside build.gradle.kts
